[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[project]
name = "maze-project"
version = "1.0.0"
authors = [
  {name="vchiling"},
  {name="vrafyan"}
  ]
description = "Maze generation and solving project"
requires-python = ">=3.10"

dependencies = [
    "pydantic>=2.0",
]


[project.optional-dependencies]
test = [
    "pytest",
    "mypy",
    "flake8",
]